<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0;net11.0</TargetFrameworks>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);CS1591;CA1707;IDE0005</NoWarn>
		<RootNamespace>Vexel.Telegram.Tests</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk"/>
		<PackageReference Include="xunit"/>
		<PackageReference Include="xunit.runner.visualstudio">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="coverlet.collector">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions"/>
		<PackageReference Include="Microsoft.Extensions.Options"/>
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit"/>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Vexel.Telegram.Client\Vexel.Telegram.Client.csproj"/>
	</ItemGroup>

</Project>
