<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable>true</IsPackable>
		<Description>ASP.NET Core webhook endpoint integration for Vexel.Telegram.</Description>
		<RootNamespace>Vexel.Telegram.AspNetCore</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App"/>
		<PackageReference Include="Microsoft.Extensions.Options"/>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Vexel.Telegram.Client\Vexel.Telegram.Client.csproj"/>
	</ItemGroup>

	<PropertyGroup Label="MinVer">
		<MinVerAutoIncrement>minor</MinVerAutoIncrement>
		<MinVerDefaultPreReleaseIdentifiers>preview.0</MinVerDefaultPreReleaseIdentifiers>
		<MinVerTagPrefix>v</MinVerTagPrefix>
	</PropertyGroup>

</Project>
