using System.Text;

namespace Vexel.Telegram.Generators;

internal static class RouteRegistrationEmitter
{
	public static string Emit(AssemblyRoutesModel model)
	{
		var sb = new StringBuilder(capacity: 2048);
		_ = sb.AppendLine("// <auto-generated />");
		_ = sb.AppendLine("#nullable enable");
		_ = sb.AppendLine();
		_ = sb.AppendLine("#pragma warning disable CS1591");
		_ = sb.AppendLine();

		if (!string.IsNullOrEmpty(model.RootNamespace))
		{
			_ = sb.Append("namespace ").Append(model.RootNamespace).AppendLine(";");
			_ = sb.AppendLine();
		}

		_ = sb.AppendLine("/// <summary>Generated Vexel Telegram route registration.</summary>");
		_ = sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"Vexel.Telegram.Generators\", \"2.0.0\")]");
		_ = sb.AppendLine("public static partial class TelegramServiceCollectionExtensions");
		_ = sb.AppendLine("{");
		_ = sb.Append("\t/// <summary>Registers Telegram routes discovered in this assembly (")
			.Append(Escape(model.AssemblyIdentifier))
			.AppendLine(").</summary>");
		_ = sb.Append("\tpublic static global::Microsoft.Extensions.DependencyInjection.IServiceCollection Add")
			.Append(model.AssemblyIdentifier)
			.AppendLine("Telegram(");
		_ = sb.AppendLine("\t\tthis global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
		_ = sb.AppendLine("\t{");
		_ = sb.AppendLine("\t\tglobal::System.ArgumentNullException.ThrowIfNull(services);");
		_ = sb.AppendLine();
		_ = sb.AppendLine("\t\tvar commands = new global::System.Collections.Generic.Dictionary<string, global::Vexel.Telegram.Handlers.Routing.RouteBinder>(");
		_ = sb.AppendLine("\t\t\tglobal::System.StringComparer.OrdinalIgnoreCase)");
		_ = sb.AppendLine("\t\t{");

		foreach (var command in model.Commands)
		{
			_ = sb.Append("\t\t\t[\"").Append(Escape(command.CommandName)).AppendLine("\"] = static async (scope, payload, cancellationToken) =>");
			_ = sb.AppendLine("\t\t\t{");
			EmitCommandBinderBody(sb, command, indent: "\t\t\t\t");
			_ = sb.AppendLine("\t\t\t},");
		}

		_ = sb.AppendLine("\t\t};");
		_ = sb.AppendLine();
		_ = sb.AppendLine("\t\tvar metadata = new global::Vexel.Telegram.Client.BotCommandDescriptor[]");
		_ = sb.AppendLine("\t\t{");

		foreach (var command in model.Commands.OrderBy(static c => c.CommandName, StringComparer.Ordinal))
		{
			var description = command.Description ?? string.Empty;
			_ = sb.Append("\t\t\tnew global::Vexel.Telegram.Client.BotCommandDescriptor(\"")
				.Append(Escape(command.CommandName))
				.Append("\", \"")
				.Append(Escape(description))
				.AppendLine("\"),");
		}

		_ = sb.AppendLine("\t\t};");
		_ = sb.AppendLine();
		EmitBinderDictionary(sb, "callbacks", model.Callbacks, static c => c.RouteKey, static c => (c.HandlerFullyQualifiedName, c.RequestFullyQualifiedName, c.HasStringParameter));
		_ = sb.AppendLine();
		EmitBinderDictionary(sb, "inlineQueries", model.InlineQueries, static c => c.Trigger, static c => (c.HandlerFullyQualifiedName, c.RequestFullyQualifiedName, c.HasStringParameter));
		_ = sb.AppendLine();
		EmitBinderDictionary(sb, "chosenInlineResults", model.ChosenInlineResults, static c => c.RouteKey, static c => (c.HandlerFullyQualifiedName, c.RequestFullyQualifiedName, c.HasStringParameter));
		_ = sb.AppendLine();
		_ = sb.AppendLine("\t\tvar flowSteps = new global::System.Collections.Generic.Dictionary<string, global::Vexel.Telegram.Handlers.Routing.RouteBinder>(");
		_ = sb.AppendLine("\t\t\tglobal::System.StringComparer.Ordinal)");
		_ = sb.AppendLine("\t\t{");

		foreach (var step in model.FlowSteps)
		{
			// Key must equal typeof(TRequest).FullName at runtime (Flow.PromptAsync / router lookup).
			_ = sb.Append("\t\t\t[typeof(")
				.Append(step.RequestFullyQualifiedName)
				.AppendLine(").FullName!] = static async (scope, payload, cancellationToken) =>");
			_ = sb.AppendLine("\t\t\t{");
			EmitStringOrEmptyBinderBody(sb, step.HandlerFullyQualifiedName, step.RequestFullyQualifiedName, step.HasStringParameter, indent: "\t\t\t\t");
			_ = sb.AppendLine("\t\t\t},");
		}

		_ = sb.AppendLine("\t\t};");
		_ = sb.AppendLine();
		EmitOnHandlerArray(sb, "onMessages", model.OnMessages);
		_ = sb.AppendLine();
		EmitOnHandlerArray(sb, "onCallbackQueries", model.OnCallbackQueries);
		_ = sb.AppendLine();
		EmitOnHandlerArray(sb, "onInlineQueries", model.OnInlineQueries);
		_ = sb.AppendLine();
		EmitOnHandlerArray(sb, "onChosenInlineResults", model.OnChosenInlineResults);
		_ = sb.AppendLine();
		_ = sb.AppendLine("\t\t_ = global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton(");
		_ = sb.AppendLine("\t\t\tservices,");
		_ = sb.AppendLine("\t\t\tnew global::Vexel.Telegram.Handlers.Routing.TelegramRouteContribution(");
		_ = sb.Append("\t\t\t\t\"").Append(Escape(model.AssemblyIdentifier)).AppendLine("\",");
		_ = sb.AppendLine("\t\t\t\tcommands,");
		_ = sb.AppendLine("\t\t\t\tmetadata,");
		_ = sb.AppendLine("\t\t\t\tcallbacks,");
		_ = sb.AppendLine("\t\t\t\tinlineQueries,");
		_ = sb.AppendLine("\t\t\t\tchosenInlineResults,");
		_ = sb.AppendLine("\t\t\t\tflowSteps,");
		_ = sb.AppendLine("\t\t\t\tonMessages,");
		_ = sb.AppendLine("\t\t\t\tonCallbackQueries,");
		_ = sb.AppendLine("\t\t\t\tonInlineQueries,");
		_ = sb.AppendLine("\t\t\t\tonChosenInlineResults));");
		_ = sb.AppendLine();
		_ = sb.AppendLine("\t\treturn services;");
		_ = sb.AppendLine("\t}");
		_ = sb.AppendLine("}");

		return sb.ToString();
	}

	private static void EmitBinderDictionary<T>(
		StringBuilder sb,
		string variableName,
		IEnumerable<T> routes,
		Func<T, string> keySelector,
		Func<T, (string Handler, string Request, bool HasString)> binderSelector)
	{
		_ = sb.Append("\t\tvar ").Append(variableName)
			.AppendLine(" = new global::System.Collections.Generic.Dictionary<string, global::Vexel.Telegram.Handlers.Routing.RouteBinder>(");
		_ = sb.AppendLine("\t\t\tglobal::System.StringComparer.Ordinal)");
		_ = sb.AppendLine("\t\t{");

		foreach (var route in routes)
		{
			var key = keySelector(route);
			var (handler, request, hasString) = binderSelector(route);
			_ = sb.Append("\t\t\t[\"").Append(Escape(key)).AppendLine("\"] = static async (scope, payload, cancellationToken) =>");
			_ = sb.AppendLine("\t\t\t{");
			EmitStringOrEmptyBinderBody(sb, handler, request, hasString, indent: "\t\t\t\t");
			_ = sb.AppendLine("\t\t\t},");
		}

		_ = sb.AppendLine("\t\t};");
	}

	private static void EmitCommandBinderBody(StringBuilder sb, CommandRouteModel command, string indent)
	{
		if (command.Parameters.Count == 0)
		{
			EmitResolveAndInvoke(sb, command.HandlerFullyQualifiedName, command.RequestFullyQualifiedName, indent, requestArgs: string.Empty);
			return;
		}

		if (command.Parameters is [{ Kind: BindableParameterKind.String }])
		{
			// Single string: whole remainder (possibly empty).
			EmitResolveAndInvoke(sb, command.HandlerFullyQualifiedName, command.RequestFullyQualifiedName, indent, requestArgs: "payload");
			return;
		}

		var trailingTakesRest = command.Parameters[^1].IsTrailingString;
		_ = sb.Append(indent)
			.Append("if (!global::Vexel.Telegram.Handlers.Routing.CommandArgumentBinder.TryTokenize(payload, ")
			.Append(command.Parameters.Count)
			.Append(", trailingTakesRest: ")
			.Append(trailingTakesRest ? "true" : "false")
			.AppendLine(", out var tokens))");
		_ = sb.Append(indent).AppendLine("{");
		_ = sb.Append(indent).AppendLine("\treturn false;");
		_ = sb.Append(indent).AppendLine("}");
		_ = sb.AppendLine();

		for (var i = 0; i < command.Parameters.Count; i++)
		{
			EmitParse(sb, command.Parameters[i], i, indent);
		}

		var args = new StringBuilder();
		for (var i = 0; i < command.Parameters.Count; i++)
		{
			if (i > 0)
			{
				_ = args.Append(", ");
			}

			_ = args.Append(command.Parameters[i].Kind == BindableParameterKind.String
				? "tokens[" + i + "]"
				: "p" + i);
		}

		EmitResolveAndInvoke(sb, command.HandlerFullyQualifiedName, command.RequestFullyQualifiedName, indent, args.ToString());
	}

	private static void EmitStringOrEmptyBinderBody(
		StringBuilder sb,
		string handlerFullyQualifiedName,
		string requestFullyQualifiedName,
		bool hasStringParameter,
		string indent)
	{
		// Empty record: ignore payload. Single string: whole payload (possibly empty).
		var requestArgs = hasStringParameter ? "payload" : string.Empty;
		EmitResolveAndInvoke(sb, handlerFullyQualifiedName, requestFullyQualifiedName, indent, requestArgs);
	}

	private static void EmitOnHandlerArray(
		StringBuilder sb,
		string variableName,
		EquatableReadOnlyList<OnHandlerModel> handlers)
	{
		_ = sb.Append("\t\tvar ").Append(variableName)
			.AppendLine(" = new global::Vexel.Telegram.Handlers.Routing.OnHandlerEntry[]");
		_ = sb.AppendLine("\t\t{");

		foreach (var handler in handlers)
		{
			_ = sb.AppendLine("\t\t\tnew global::Vexel.Telegram.Handlers.Routing.OnHandlerEntry(");
			_ = sb.Append("\t\t\t\t\"").Append(Escape(handler.HandlerFullyQualifiedName)).AppendLine("\",");
			_ = sb.AppendLine("\t\t\t\tstatic async (scope, payload, cancellationToken) =>");
			_ = sb.AppendLine("\t\t\t\t{");
			// On* requests are empty records; payload is ignored.
			EmitResolveAndInvoke(
				sb,
				handler.HandlerFullyQualifiedName,
				handler.RequestFullyQualifiedName,
				indent: "\t\t\t\t\t",
				requestArgs: string.Empty);
			_ = sb.AppendLine("\t\t\t\t}),");
		}

		_ = sb.AppendLine("\t\t};");
	}

	private static void EmitResolveAndInvoke(
		StringBuilder sb,
		string handlerFullyQualifiedName,
		string requestFullyQualifiedName,
		string indent,
		string requestArgs)
	{
		_ = sb.Append(indent)
			.Append("var handler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<")
			.Append(handlerFullyQualifiedName)
			.AppendLine(".Handler>(scope);");
		_ = sb.Append(indent)
			.Append("_ = await handler.HandleAsync(new ")
			.Append(requestFullyQualifiedName)
			.Append('(')
			.Append(requestArgs)
			.AppendLine("), cancellationToken).ConfigureAwait(false);");
		_ = sb.Append(indent).AppendLine("return true;");
	}

	private static void EmitParse(StringBuilder sb, RequestParameterModel parameter, int index, string indent)
	{
		var parseCall = parameter.Kind switch
		{
			BindableParameterKind.String => null,
			BindableParameterKind.Int =>
				"global::Vexel.Telegram.Handlers.Routing.CommandArgumentBinder.TryParseInt(tokens[" + index + "], out var p" + index + ")",
			BindableParameterKind.Long =>
				"global::Vexel.Telegram.Handlers.Routing.CommandArgumentBinder.TryParseLong(tokens[" + index + "], out var p" + index + ")",
			BindableParameterKind.Bool =>
				"global::Vexel.Telegram.Handlers.Routing.CommandArgumentBinder.TryParseBool(tokens[" + index + "], out var p" + index + ")",
			BindableParameterKind.Decimal =>
				"global::Vexel.Telegram.Handlers.Routing.CommandArgumentBinder.TryParseDecimal(tokens[" + index + "], out var p" + index + ")",
			BindableParameterKind.Enum =>
				"global::Vexel.Telegram.Handlers.Routing.CommandArgumentBinder.TryParseEnum<"
				+ parameter.FullyQualifiedTypeName
				+ ">(tokens[" + index + "], out var p" + index + ")",
			_ => throw new InvalidOperationException("Unexpected kind " + parameter.Kind),
		};

		if (parseCall is null)
		{
			// Token already a string; no parse step.
			return;
		}

		_ = sb.Append(indent).Append("if (!").Append(parseCall).AppendLine(")");
		_ = sb.Append(indent).AppendLine("{");
		_ = sb.Append(indent).AppendLine("\treturn false;");
		_ = sb.Append(indent).AppendLine("}");
		_ = sb.AppendLine();
	}

	private static string Escape(string value) => Utility.EscapeString(value);
}
